/* WRITE Settlement Manager V8.2.0 — Semantic FACT Core (Shadow) */
(function(g){'use strict';
const VERSION='8.2.0';
const ROLE=Object.freeze({MAIN:'MAIN',UPSELL:'UPSELL',SERVICE:'SERVICE',FEE:'FEE',FREE_GIFT:'FREE_GIFT',STOCK:'STOCK',UNKNOWN:'UNKNOWN'});
const QTY=Object.freeze({MATCHING_ORDERS:'MATCHING_ORDERS',ACTUAL_UNITS:'ACTUAL_UNITS',SERVICE_UNITS:'SERVICE_UNITS',AFFECTED_ORDERS:'AFFECTED_ORDERS',EXCLUDED:'EXCLUDED',BEST_EFFORT:'BEST_EFFORT'});
const SCOPE_RANK=Object.freeze({CURRENT_ORDER:60,EXACT_SKU:50,EXACT_PRODUCT:40,PRODUCT_FAMILY:30,ORDER_CONTEXT:20,GLOBAL_PATTERN:10});
const SOURCE_RANK=Object.freeze({HUMAN_CORRECTION:600,VERIFIED_MANUAL_FACT:500,HUMAN_CONFIRMED_RULE:450,VERIFIED_HISTORICAL_RULE:400,SYSTEM_HIGH_CONFIDENCE:300,SYSTEM_INFERENCE:200,FALLBACK:100});
const clean=v=>String(v??'').replace(/\r/g,' ').replace(/\s+/g,' ').trim();
const lower=v=>clean(v).toLowerCase();
const finite=v=>v===null||v===undefined||v===''?null:(Number.isFinite(Number(v))?Number(v):null);
const clamp=v=>Math.max(0,Math.min(1,Number(v)||0));
function dims(t){const m=clean(t).match(/(\d+(?:[.,]\d+)?)\s*(?:m(?:米)?\s*)?[x×*]\s*(\d+(?:[.,]\d+)?)(?:\s*(?:m(?:米)?\s*)?[x×*]\s*(\d+(?:[.,]\d+)?))?/i);return m?[m[1],m[2],m[3]].filter(Boolean).map(x=>x.replace(',','.')).join('x'):''}
function qtyFromSku(s){const m=clean(s).match(/(?:\*|×|x)\s*(\d+(?:[.,]\d+)?)\s*$/i);if(!m)return null;const n=Number(m[1].replace(',','.'));return Number.isFinite(n)&&n>0?n:null}
function freeGift(t){return /100\s*%\s*off|gratuit|cadeau|free\s*gift|offert/i.test(clean(t))}
function placeholderText(t){return /^(?:48|97|n\/?a|na|none|null|unknown|inconnu|待确认|未知|[-—–]+)$/i.test(clean(t))}
const familyRules=[
 ['CAMOUFLAGE_NET_TRIANGLE',/filet\s+de\s+camouflage.*triang|triang(?:ulaire|le|形).*?(?:filet|网)|(?:filet|网).*?triang(?:ulaire|le|形)|三角形?网/i],
 ['CAMOUFLAGE_NET',/filet\s+de\s+camouflage/i],['FIXATION_KIT',/kit\s+de\s+fixation/i],['CABLE_TIE',/colliers?\s+de\s+serrage/i],['RATCHET_CORD',/cordes?\s+à\s+cliquets/i],['FIXATION_ROPE',/corde\s+de\s+fixation|椰棕纤维绳|椰子纤维绳/i],
 ['COLLAGEN_JELLY',/gel[ée]e?\s+au\s+collag[èe]ne|collagen.*jelly/i],['CHEMISE',/\bchemise\b/i],['GILET_KRYONIFY',/\bgilet\b.*kryonify|kryonify.*gilet/i],['PENCIL_REFILL',/mine(?:s)?\s+(?:rechargeable|color[ée]e)|refill/i],['PENCIL',/stylo\s+[ée]ternel|crayon\s+[ée]ternel|pencil/i],['GIFT_BOX',/coffret\s+cadeau|gift\s+box/i],['ENGRAVING_SERVICE',/gravure|engraving/i],['IMPORT_FEE',/frais\s+d.?importation|import\s+fee/i]
];
function familyInference(item){const t=[item?.productName,item?.sku].map(clean).join(' ');if(placeholderText(item?.productName)&&placeholderText(item?.sku))return{family:'PLACEHOLDER_NON_PRODUCT',confidence:1,evidence:['source:placeholder-non-product']};for(const [family,re] of familyRules)if(re.test(t))return{family,confidence:.98,evidence:[`pattern:${family}`]};const token=clean(item?.productName)||clean(item?.sku)||'UNKNOWN_PRODUCT';return{family:`NEW:${token.slice(0,48)}`,confidence:.42,evidence:['fallback:new-family']}}
function accountingDimensions(family,item){const size=dims(item?.productName);if(['CAMOUFLAGE_NET','CAMOUFLAGE_NET_TRIANGLE'].includes(family)&&size)return{size};if(family==='FIXATION_ROPE'){const m=clean(item?.productName).match(/(\d+(?:[.,]\d+)?)\s*(m|cm|mm)\b/i);if(m)return{length:`${m[1].replace(',','.')}${m[2].toLowerCase()}`}}return{}}
function description(family,item){const d=accountingDimensions(family,item);if(family==='PLACEHOLDER_NON_PRODUCT')return clean(item?.productName)||clean(item?.sku)||'Placeholder';if(family==='CAMOUFLAGE_NET')return`Le Filet de camouflage${d.size?` / ${d.size}`:''}`;if(family==='CAMOUFLAGE_NET_TRIANGLE')return`Le Filet de camouflage Triangulaire${d.size?` / ${d.size}`:''}`;if(family==='FIXATION_KIT')return'Kit de fixation complet - Suspendu';if(family==='CABLE_TIE')return'Colliers de serrage x100 - pergola';if(family==='RATCHET_CORD')return'Cordes à cliquets réglables - Lot de 4';if(family==='COLLAGEN_JELLY')return'Gelée au collagène';if(family==='CHEMISE')return'Chemise';if(family==='GILET_KRYONIFY')return'Gilet Kryonify';if(family==='PENCIL')return'Stylo eternel';if(family==='GIFT_BOX')return'Coffret Cadeau';if(family==='ENGRAVING_SERVICE')return'Gravure Personnalisée';if(family==='IMPORT_FEE')return"Frais d’importation dans l’UE";if(family==='FIXATION_ROPE'){const len=d.length?` / ${d.length}`:'';return`Corde de fixation polyester tressée${len}`};const raw=clean(item?.productName)||clean(item?.sku)||'Article';return raw.length>72?raw.slice(0,72).replace(/\s+\S*$/,''):raw}
function roleInference(item,ctx={}){const fam=item.semanticFamily||familyInference(item).family,companions=ctx.families||[];if(fam==='PLACEHOLDER_NON_PRODUCT')return{role:ROLE.UNKNOWN,confidence:1,evidence:['source:placeholder-non-product']};if(freeGift(`${item?.productName||''} ${item?.sku||''}`))return{role:ROLE.FREE_GIFT,confidence:.99,evidence:['free-gift']};if(fam==='ENGRAVING_SERVICE'||fam==='GIFT_BOX')return{role:ROLE.SERVICE,confidence:.95,evidence:['service-family']};if(fam==='IMPORT_FEE')return{role:ROLE.FEE,confidence:.99,evidence:['fee-family']};const net=companions.some(x=>x==='CAMOUFLAGE_NET'||x==='CAMOUFLAGE_NET_TRIANGLE');if(net&&['FIXATION_KIT','CABLE_TIE','RATCHET_CORD'].includes(fam))return{role:ROLE.UPSELL,confidence:.96,evidence:['context:camouflage-accessory']};if(companions.includes('PENCIL')&&fam==='PENCIL_REFILL')return{role:ROLE.UPSELL,confidence:.94,evidence:['context:pencil-refill']};if(fam.startsWith('NEW:'))return{role:ROLE.MAIN,confidence:.58,evidence:['fallback:new-main']};return{role:ROLE.MAIN,confidence:.88,evidence:['default-main']}}
function quantityStrategy(role){return role===ROLE.MAIN?QTY.MATCHING_ORDERS:role===ROLE.UPSELL?QTY.ACTUAL_UNITS:role===ROLE.SERVICE?QTY.SERVICE_UNITS:role===ROLE.FEE?QTY.AFFECTED_ORDERS:role===ROLE.FREE_GIFT?QTY.EXCLUDED:role===ROLE.STOCK?QTY.ACTUAL_UNITS:QTY.BEST_EFFORT}
function normalizeRule(r={}){return{id:clean(r.id)||`rule:${Math.random().toString(36).slice(2)}`,sourceType:clean(r.sourceType)||'SYSTEM_INFERENCE',scope:clean(r.scope)||'GLOBAL_PATTERN',confidence:clamp(r.confidence??.5),humanConfirmed:!!r.humanConfirmed,updatedAt:Number(r.updatedAt)||0,version:Number(r.version)||1,pattern:r.pattern||{},action:r.action||{},sourceRef:r.sourceRef||null}}
function priority(r){r=normalizeRule(r);return[(r.humanConfirmed?1000:0)+(SOURCE_RANK[r.sourceType]||0),SCOPE_RANK[r.scope]||0,r.confidence,r.updatedAt,r.version]}
function compareRules(a,b){const aa=priority(a),bb=priority(b);for(let i=0;i<aa.length;i++)if(aa[i]!==bb[i])return bb[i]-aa[i];return clean(a.id).localeCompare(clean(b.id))}
function matchRule(r,c){const p=r.pattern||{};if(p.orderKey&&clean(p.orderKey)!==clean(c.orderKey))return false;if(p.sku&&lower(p.sku)!==lower(c.sku))return false;if(p.product&&lower(p.product)!==lower(c.productName))return false;if(p.family&&p.family!==c.family)return false;if(p.role&&p.role!==c.role)return false;if(p.country&&lower(p.country)!==lower(c.country))return false;if(p.companionFamily&&!(c.companionFamilies||[]).includes(p.companionFamily))return false;return true}
function resolveRules(rules,ctx){const m=(rules||[]).map(normalizeRule).filter(r=>matchRule(r,ctx)).sort(compareRules),winner=m[0]||null,conflicts=[];if(winner)for(const r of m.slice(1))if(JSON.stringify(r.action)!==JSON.stringify(winner.action))conflicts.push({winner:winner.id,challenger:r.id});return{winner,matches:m,conflicts}}
function itemQty(x){if(placeholderText(x?.productName)&&placeholderText(x?.sku))return 0;return finite(x?.quantity)??qtyFromSku(x?.sku)??1}
function sourceOrderKey(order){return clean(order?.recordKey||order?.orderId)||`ROW:${Number(order?.sourceRow||0)}`}
function sourceItemKey(order,item,itemIndex){return `${sourceOrderKey(order)}::${itemIndex}::${clean(item?.sku)}::${clean(item?.productName)}`}
function semanticizeOrder(order,rules=[]){
 const raw=(order?.lineItems||[]).filter(x=>clean(x?.productName)||clean(x?.sku));
 const fam=raw.map((x,i)=>({...x,sourceItemKey:sourceItemKey(order,x,i),sourceQuantity:itemQty(x),...familyInference(x)}));
 const families=fam.map(x=>x.family),items=[];
 for(const x of fam){
  const rg=roleInference({...x,semanticFamily:x.family},{families}),ctx={orderKey:sourceOrderKey(order),sku:clean(x.sku),productName:clean(x.productName),family:x.family,role:rg.role,country:clean(order?.country),companionFamilies:families.filter(f=>f!==x.family)},rr=resolveRules(rules,ctx),a=rr.winner?.action||{},family=a.family||x.family,role=a.role||rg.role,confidence=Math.min(a.family?1:x.confidence,a.role?1:rg.confidence);
  items.push({productName:clean(x.productName),sku:clean(x.sku),sourceItemKey:x.sourceItemKey,sourceQuantity:x.sourceQuantity,family,role,quantity:itemQty(x),quantityStrategy:a.quantityStrategy||quantityStrategy(role),description:a.description||description(family,x),confidence,needsReview:confidence<.75||rr.conflicts.length>0||family.startsWith('NEW:'),evidence:[...(x.evidence||[]),...(rg.evidence||[]),...(rr.winner?[`rule:${rr.winner.id}`]:[])],conflicts:rr.conflicts,ruleId:rr.winner?.id||null})
 }
 return{orderKey:sourceOrderKey(order),country:clean(order?.country)||'GLOBAL',sourceFile:clean(order?.sourceFile),sourceRow:Number(order?.sourceRow)||0,items}
}
function signature(o){const main=o.items.filter(x=>x.role===ROLE.MAIN).map(x=>`${x.family}[${JSON.stringify(accountingDimensions(x.family,x))}]*${x.quantity}`).sort();return main.join('+')||'NO_MAIN'}
function aggregate(orders){const gmap=new Map();const add=(key,row,q)=>{let g=gmap.get(key);if(!g){g={...row,quantity:0,sourceOrderKeys:[],sourceItemKeys:[],confidence:1,needsReview:false,traceId:`V82:${gmap.size+1}`};gmap.set(key,g)}g.quantity+=q;g.confidence=Math.min(g.confidence,row.confidence??1);g.needsReview||=!!row.needsReview;if(row.orderKey)g.sourceOrderKeys.push(row.orderKey);if(Array.isArray(row.sourceItemKeys))g.sourceItemKeys.push(...row.sourceItemKeys)};
 for(const o of orders){
  const mains=o.items.filter(x=>x.role===ROLE.MAIN);
  if(mains.length){const sig=signature(o),desc=mains.map(x=>x.description+(x.quantity>1?` *${x.quantity}`:'')).join('\n');add(`${o.country}\u0001MAIN\u0001${sig}`,{country:o.country,role:ROLE.MAIN,description:desc,signature:sig,quantityStrategy:QTY.MATCHING_ORDERS,confidence:Math.min(...mains.map(x=>x.confidence)),needsReview:mains.some(x=>x.needsReview),orderKey:o.orderKey,sourceItemKeys:mains.map(x=>x.sourceItemKey)},1)}
  for(const x of o.items){
   if(x.role===ROLE.UPSELL)add(`${o.country}\u0001UPSELL\u0001${x.family}\u0001${x.description}`,{country:o.country,role:x.role,description:`${x.description} UPSELL`,signature:x.family,quantityStrategy:QTY.ACTUAL_UNITS,confidence:x.confidence,needsReview:x.needsReview,orderKey:o.orderKey,sourceItemKeys:[x.sourceItemKey]},x.quantity);
   else if(x.role===ROLE.SERVICE)add(`${o.country}\u0001SERVICE\u0001${x.family}`,{country:o.country,role:x.role,description:x.description,signature:x.family,quantityStrategy:QTY.SERVICE_UNITS,confidence:x.confidence,needsReview:x.needsReview,orderKey:o.orderKey,sourceItemKeys:[x.sourceItemKey]},x.quantity);
   else if(x.role===ROLE.FEE)add(`${o.country}\u0001FEE\u0001${x.family}`,{country:o.country,role:x.role,description:x.description,signature:x.family,quantityStrategy:QTY.AFFECTED_ORDERS,confidence:x.confidence,needsReview:x.needsReview,orderKey:o.orderKey,sourceItemKeys:[x.sourceItemKey]},1)
  }
 }
 return[...gmap.values()]
}
function audit(orders,rules=[]){const semanticOrders=(orders||[]).map(o=>semanticizeOrder(o,rules)),rows=aggregate(semanticOrders),items=semanticOrders.flatMap(o=>o.items),conflicts=items.flatMap(x=>x.conflicts||[]);return{version:VERSION,sourceOrders:(orders||[]).length,sourceItems:items.length,semanticOrders,factShadowRows:rows,ruleCoverage:{confirmed:items.filter(x=>x.ruleId&&!x.needsReview).length,inferred:items.filter(x=>!x.ruleId&&!x.needsReview).length,needsReview:items.filter(x=>x.needsReview).length,conflicts:conflicts.length,unknownFamily:items.filter(x=>String(x.family).startsWith('NEW:')).length},conflicts}}
function classifyTrainingDocument(m={}){if(m.corrupt||m.parseError)return{status:'REJECTED',reason:'SOURCE_UNREADABLE'};if(!m.hasFact||!m.factRows)return{status:'REFERENCE_ONLY',reason:'NO_USABLE_FACT'};if(!m.hasOrderSource)return{status:'REFERENCE_ONLY',reason:'NO_MATCHING_ORDER_SOURCE'};const c=finite(m.coverage);if(c===null)return{status:'PARTIAL',reason:'COVERAGE_UNVERIFIED'};if(c>=.999999)return{status:'COMPLETE',reason:'SOURCE_FACT_CLOSED_LOOP'};return{status:'PARTIAL',reason:`COVERAGE_${Math.round(c*10000)/100}%`}}
g.WRITE_SEMANTIC_V8=Object.freeze({VERSION,ROLE,QTY,SCOPE_RANK,SOURCE_RANK,familyInference,accountingDimensions,standardizedDescription:description,roleInference,quantityStrategy,normalizeRule,rulePriority:priority,compareRulePriority:compareRules,matchesRule:matchRule,resolveRules,semanticizeOrder,configurationSignature:signature,aggregateSemanticOrders:aggregate,audit,classifyTrainingDocument});
})(typeof window!=='undefined'?window:globalThis);
