const state={items:[],transactions:[],shipments:[],shipmentLines:[],templateBuffer:null,templateName:'inventory-template.xlsx'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const toast=msg=>{const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)};
const fmtDate=v=>{if(!v)return'';try{return new Intl.DateTimeFormat('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return v}};
const esc=s=>String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
async function api(body){const r=await fetch('/api/inventory',body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||`HTTP ${r.status}`);return j}
async function refresh(){try{const j=await api();Object.assign(state,j);renderAll();$('#syncText').textContent='Cloudflare 已同步';$('.dot').classList.add('ok')}catch(e){$('#syncText').textContent='同步失败';$('.dot').classList.remove('ok');toast(e.message)}}
function renderAll(){renderDashboard();renderInventory();renderShipping();renderTx();populateStockRows()}
function renderDashboard(){
 const total=state.items.reduce((a,x)=>a+Number(x.remaining_qty||0),0), out=state.items.reduce((a,x)=>a+Number(x.outbound_qty||0),0), skus=new Set(state.items.map(x=>String(x.sku).toLowerCase())).size, pending=state.shipments.filter(x=>!x.tracking_no).length;
 $('#kpiStock').textContent=total;$('#kpiOut').textContent=out;$('#kpiSku').textContent=skus;$('#kpiPending').textContent=pending;
 const low=[...state.items].filter(x=>Number(x.remaining_qty)<=10).sort((a,b)=>Number(a.remaining_qty)-Number(b.remaining_qty)).slice(0,8);
 $('#lowStockList').innerHTML=low.length?low.map(x=>`<div class="stack-item"><div><b>${esc(x.sku)}</b><br><small>${esc(x.carton||'未分箱')}</small></div><span class="badge ${Number(x.remaining_qty)<=3?'bad':'warn'}">剩 ${x.remaining_qty}</span></div>`).join(''):'<div class="empty">暂无低库存</div>';
 $('#recentShipList').innerHTML=state.shipments.slice(0,8).map(x=>`<div class="stack-item"><div><b>${esc(x.shipment_no)}</b><br><small>${esc(x.order_no||'无订单号')} · ${fmtDate(x.created_at)}</small></div><span class="badge ${x.tracking_no?'good':'warn'}">${x.tracking_no?esc(x.tracking_no):'待运单'}</span></div>`).join('')||'<div class="empty">暂无发货记录</div>';
}
function renderInventory(){const q=$('#inventorySearch').value.trim().toLowerCase();const rows=state.items.filter(x=>!q||`${x.carton} ${x.sku}`.toLowerCase().includes(q));$('#inventoryBody').innerHTML=rows.map(x=>`<tr><td>${esc(x.carton||'—')}</td><td><b>${esc(x.sku)}</b></td><td class="num">${x.opening_qty}</td><td class="num">${x.outbound_qty}</td><td class="num ${Number(x.remaining_qty)<=3?'low':''}">${x.remaining_qty}</td><td>${x.source_row||'手工'}</td><td><div class="row-actions"><button class="mini-btn blue" data-stock-row="${esc(x.row_key)}">入库</button><button class="mini-btn" data-ship-row="${esc(x.row_key)}">发货</button></div></td></tr>`).join('')||'<tr><td colspan="7"><div class="empty">没有库存数据</div></td></tr>'}
function shipmentLineText(no){const ls=state.shipmentLines.filter(x=>x.shipment_no===no);return ls.map(x=>`${x.sku} × ${x.qty}`).join('<br>')||'—'}
function renderShipping(){const q=$('#shippingSearch').value.trim().toLowerCase();const rows=state.shipments.filter(x=>!q||`${x.shipment_no} ${x.order_no||''} ${x.tracking_no||''}`.toLowerCase().includes(q));$('#shippingBody').innerHTML=rows.map(x=>`<tr><td><b>${esc(x.shipment_no)}</b></td><td>${esc(x.order_no||'—')}</td><td>${shipmentLineText(x.shipment_no)}</td><td>${esc(x.carrier||'—')}</td><td>${x.tracking_no?`<b>${esc(x.tracking_no)}</b>`:'<span class="badge warn">待补填</span>'}</td><td><span class="badge ${x.tracking_no?'good':'warn'}">${x.tracking_no?'已发货':'待运单'}</span></td><td>${fmtDate(x.created_at)}</td><td><div class="row-actions"><button class="mini-btn blue" data-track="${esc(x.shipment_no)}">运单</button><button class="mini-btn red" data-delship="${esc(x.shipment_no)}">撤销</button></div></td></tr>`).join('')||'<tr><td colspan="8"><div class="empty">暂无发货记录</div></td></tr>'}
function renderTx(){$('#txBody').innerHTML=state.transactions.map(x=>`<tr><td>${fmtDate(x.created_at)}</td><td><span class="badge ${x.tx_type==='IN'?'good':'warn'}">${x.tx_type==='IN'?'入库':'出库'}</span></td><td>${esc(x.carton||'—')}</td><td>${esc(x.sku)}</td><td>${x.qty}</td><td>${esc(x.order_no||'—')}</td><td>${esc(x.tracking_no||'—')}</td><td>${esc(x.note||'')}</td></tr>`).join('')||'<tr><td colspan="8"><div class="empty">暂无流水</div></td></tr>'}
function populateStockRows(){$('#stockRow').innerHTML='<option value="">新增 SKU / 箱号</option>'+state.items.map(x=>`<option value="${esc(x.row_key)}">${esc(x.carton||'—')} · ${esc(x.sku)} · 剩 ${x.remaining_qty}</option>`).join('')}
function openStock(rowKey=''){populateStockRows();$('#stockRow').value=rowKey;const x=state.items.find(i=>i.row_key===rowKey);$('#stockCarton').value=x?.carton||'';$('#stockSku').value=x?.sku||'';$('#stockQty').value='';$('#stockNote').value='';$('#stockDialog').showModal()}
function addShipLine(rowKey=''){const d=document.createElement('div');d.className='ship-line';d.innerHTML=`<select class="ship-row"><option value="">选择 SKU / 箱号</option>${state.items.filter(x=>Number(x.remaining_qty)>0).map(x=>`<option value="${esc(x.row_key)}" ${x.row_key===rowKey?'selected':''}>${esc(x.carton||'—')} · ${esc(x.sku)} · 可用 ${x.remaining_qty}</option>`).join('')}</select><input class="ship-qty" type="number" min="1" value="1"><button type="button" class="remove-line">×</button>`;$('#shipLines').appendChild(d)}
function openShip(rowKey=''){['#shipOrder','#shipCarrier','#shipTracking','#shipNote'].forEach(s=>$(s).value='');$('#shipLines').innerHTML='';addShipLine(rowKey);$('#shipDialog').showModal()}
async function importWorkbook(file){const buf=await file.arrayBuffer();state.templateBuffer=buf.slice(0);state.templateName=file.name;const wb=XLSX.read(buf,{type:'array',cellFormula:true,cellStyles:true});const name=wb.SheetNames.includes('9月1日盘点')?'9月1日盘点':wb.SheetNames.find(n=>/盘点|库存/i.test(n));if(!name)throw new Error('未找到“9月1日盘点”或库存工作表');const ws=wb.Sheets[name];const matrix=XLSX.utils.sheet_to_json(ws,{header:1,raw:true,defval:null});const rows=[];let lastCarton='';for(let i=1;i<matrix.length;i++){const r=matrix[i]||[];let carton=(r[0]??'').toString().trim();if(carton)lastCarton=carton;else carton=lastCarton;const sku=(r[1]??'').toString().trim();const opening=Number(r[2]||0);if(!sku||!Number.isFinite(opening))continue;const outbound=Number(r[3]||0)||0;rows.push({rowKey:`row:${i+1}:${sku}`,carton,sku,openingQty:Math.trunc(opening),outboundQty:Math.trunc(outbound),remainingQty:Math.trunc(opening-outbound),sourceRow:i+1})}
 await api({action:'replace_inventory',rows});$('#fileStatus').textContent=`已导入 ${file.name} · ${rows.length} 行库存`;toast(`已同步 ${rows.length} 行库存`);await refresh()}
function xmlEscape(s){return String(s??'').replace(/[<>&'"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','"':'&quot;'}[c]))}
function colName(n){let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)}return s}
async function getBaseTemplate(){if(state.templateBuffer)return state.templateBuffer.slice(0);const r=await fetch('/assets/inventory-template.xlsx');if(!r.ok)throw new Error('默认模板读取失败');return await r.arrayBuffer()}
async function exportWorkbook(){
 const buf=await getBaseTemplate(), zip=await JSZip.loadAsync(buf);const wbXml=await zip.file('xl/workbook.xml').async('string');const relXml=await zip.file('xl/_rels/workbook.xml.rels').async('string');const doc=new DOMParser().parseFromString(wbXml,'application/xml');const sheets=[...doc.getElementsByTagNameNS('*','sheet')];const sh=sheets.find(x=>x.getAttribute('name')==='9月1日盘点')||sheets.find(x=>/盘点|库存/i.test(x.getAttribute('name')||''));if(!sh)throw new Error('模板中找不到库存工作表');const rid=sh.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id')||sh.getAttribute('r:id');const relDoc=new DOMParser().parseFromString(relXml,'application/xml');const rel=[...relDoc.getElementsByTagNameNS('*','Relationship')].find(x=>x.getAttribute('Id')===rid);if(!rel)throw new Error('库存工作表关系缺失');let target=rel.getAttribute('Target');target=target.startsWith('/')?target.slice(1):'xl/'+target.replace(/^\.\//,'');target=target.replace('xl/xl/','xl/');let sheetXml=await zip.file(target).async('string');
 for(const item of state.items){if(!item.source_row)continue;const cell=`D${item.source_row}`;const val=Number(item.outbound_qty||0);const re=new RegExp(`(<c[^>]*\br="${cell}"[^>]*>)([\s\S]*?)(<\/c>)`);if(re.test(sheetXml)){sheetXml=sheetXml.replace(re,(m,open,inner,close)=>{const next=inner.replace(/<f[\s\S]*?<\/f>/g,'').replace(/<v[\s\S]*?<\/v>/g,'');return `${open}${next}<v>${val}</v>${close}`})}else{const rowRe=new RegExp(`(<row[^>]*\br="${item.source_row}"[^>]*>)`);const node=`<c r="${cell}"><v>${val}</v></c>`;sheetXml=sheetXml.replace(rowRe,`$1${node}`)}}
 zip.file(target,sheetXml);
 // Add or replace a shipment summary worksheet with plain inline strings.
 const summaryName='发货汇总';let existing=sheets.find(x=>x.getAttribute('name')===summaryName);let summaryTarget=null,summaryRid=null;
 if(existing){summaryRid=existing.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id')||existing.getAttribute('r:id');const rr=[...relDoc.getElementsByTagNameNS('*','Relationship')].find(x=>x.getAttribute('Id')===summaryRid);summaryTarget='xl/'+rr.getAttribute('Target').replace(/^\.\//,'').replace(/^xl\//,'');}
 else{
   const ids=sheets.map(x=>Number(x.getAttribute('sheetId')||0));const nextId=Math.max(0,...ids)+1;const rels=[...relDoc.getElementsByTagNameNS('*','Relationship')];let maxRid=0;for(const r of rels){const m=(r.getAttribute('Id')||'').match(/rId(\d+)/);if(m)maxRid=Math.max(maxRid,Number(m[1]))}summaryRid=`rId${maxRid+1}`;let maxSheet=0;for(const n of Object.keys(zip.files)){const m=n.match(/^xl\/worksheets\/sheet(\d+)\.xml$/);if(m)maxSheet=Math.max(maxSheet,Number(m[1]))}summaryTarget=`xl/worksheets/sheet${maxSheet+1}.xml`;
   const parser=new DOMParser();const wdoc=parser.parseFromString(wbXml,'application/xml');const wsheets=wdoc.getElementsByTagNameNS('*','sheets')[0];const ns=wdoc.documentElement.namespaceURI;const sn=wdoc.createElementNS(ns,'sheet');sn.setAttribute('name',summaryName);sn.setAttribute('sheetId',String(nextId));sn.setAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','r:id',summaryRid);wsheets.appendChild(sn);zip.file('xl/workbook.xml',new XMLSerializer().serializeToString(wdoc));
   const rdoc=parser.parseFromString(relXml,'application/xml');const root=rdoc.documentElement;const rn=rdoc.createElementNS(root.namespaceURI,'Relationship');rn.setAttribute('Id',summaryRid);rn.setAttribute('Type','http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet');rn.setAttribute('Target',summaryTarget.replace(/^xl\//,''));root.appendChild(rn);zip.file('xl/_rels/workbook.xml.rels',new XMLSerializer().serializeToString(rdoc));
   const ctPath='[Content_Types].xml';const ct=await zip.file(ctPath).async('string');const ctdoc=parser.parseFromString(ct,'application/xml');const types=ctdoc.documentElement;const ov=ctdoc.createElementNS(types.namespaceURI,'Override');ov.setAttribute('PartName','/'+summaryTarget);ov.setAttribute('ContentType','application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml');types.appendChild(ov);zip.file(ctPath,new XMLSerializer().serializeToString(ctdoc));
 }
 const headers=['发货单号','订单号','箱号','SKU','数量','承运商','运单号','状态','发货时间','备注'];const rows=[headers];for(const s of state.shipments){const ls=state.shipmentLines.filter(x=>x.shipment_no===s.shipment_no);if(ls.length){for(const l of ls)rows.push([s.shipment_no,s.order_no||'',l.carton||'',l.sku,l.qty,s.carrier||'',s.tracking_no||'',s.tracking_no?'已发货':'待运单',s.created_at||'',s.note||''])}else rows.push([s.shipment_no,s.order_no||'','','','',s.carrier||'',s.tracking_no||'',s.tracking_no?'已发货':'待运单',s.created_at||'',s.note||''])}
 let sheetData='';rows.forEach((r,ri)=>{let cells='';r.forEach((v,ci)=>{const ref=`${colName(ci+1)}${ri+1}`;if(typeof v==='number')cells+=`<c r="${ref}"><v>${v}</v></c>`;else cells+=`<c r="${ref}" t="inlineStr"><is><t>${xmlEscape(v)}</t></is></c>`});sheetData+=`<row r="${ri+1}">${cells}</row>`});const summaryXml=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"/></sheetViews><sheetFormatPr defaultRowHeight="15"/><cols><col min="1" max="10" width="18" customWidth="1"/></cols><sheetData>${sheetData}</sheetData></worksheet>`;zip.file(summaryTarget,summaryXml);
 const out=await zip.generateAsync({type:'blob',compression:'DEFLATE'});const a=document.createElement('a');a.href=URL.createObjectURL(out);a.download=`NEOVORA_库存_${new Date().toISOString().slice(0,10)}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000);toast('Excel 已导出')
}

$$('.nav-item').forEach(b=>b.onclick=()=>{const v=b.dataset.view;$$('.nav-item').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${v}`));const meta={dashboard:['库存概览','实时库存、出库与发货状态'],inventory:['库存管理','按箱号与 SKU 管理库存'],shipping:['发货管理','创建发货、补录运单并自动扣减库存'],transactions:['库存流水','查看全部入库与出库记录'],excel:['Excel 导入 / 导出','沿用原模板并保持原规格回填']}[v];$('#pageTitle').textContent=meta[0];$('#pageDesc').textContent=meta[1]});
$$('[data-jump]').forEach(b=>b.onclick=()=>document.querySelector(`.nav-item[data-view="${b.dataset.jump}"]`).click());
$('#refreshBtn').onclick=refresh;$('#quickShipBtn').onclick=()=>openShip();$('#createShipmentBtn').onclick=()=>openShip();$('#stockInBtn').onclick=()=>openStock();$('#addShipLineBtn').onclick=()=>addShipLine();
$('#inventorySearch').oninput=renderInventory;$('#shippingSearch').oninput=renderShipping;
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.stockRow)openStock(b.dataset.stockRow);if(b.dataset.shipRow)openShip(b.dataset.shipRow);if(b.classList.contains('remove-line'))b.closest('.ship-line').remove();if(b.dataset.track){const s=state.shipments.find(x=>x.shipment_no===b.dataset.track);$('#trackingShipmentNo').value=s.shipment_no;$('#trackingCarrier').value=s.carrier||'';$('#trackingNo').value=s.tracking_no||'';$('#trackingDialog').showModal()}if(b.dataset.delship&&confirm('撤销此发货单并恢复对应库存？'))api({action:'delete_shipment',shipmentNo:b.dataset.delship}).then(()=>refresh()).then(()=>toast('发货单已撤销')).catch(x=>toast(x.message))});
$('#stockRow').onchange=()=>{const x=state.items.find(i=>i.row_key===$('#stockRow').value);if(x){$('#stockCarton').value=x.carton||'';$('#stockSku').value=x.sku||''}else{$('#stockCarton').value='';$('#stockSku').value=''}};
$('#stockSaveBtn').onclick=async e=>{e.preventDefault();try{await api({action:'stock_in',rowKey:$('#stockRow').value,carton:$('#stockCarton').value,sku:$('#stockSku').value,qty:Number($('#stockQty').value),note:$('#stockNote').value});$('#stockDialog').close();await refresh();toast('入库完成')}catch(x){toast(x.message)}};
$('#shipSaveBtn').onclick=async e=>{e.preventDefault();try{const lines=$$('#shipLines .ship-line').map(d=>({rowKey:d.querySelector('.ship-row').value,qty:Number(d.querySelector('.ship-qty').value)})).filter(x=>x.rowKey&&x.qty>0);await api({action:'ship',orderNo:$('#shipOrder').value,carrier:$('#shipCarrier').value,trackingNo:$('#shipTracking').value,note:$('#shipNote').value,lines});$('#shipDialog').close();await refresh();toast('发货单已创建，库存已扣减')}catch(x){toast(x.message)}};
$('#trackingSaveBtn').onclick=async e=>{e.preventDefault();try{await api({action:'update_tracking',shipmentNo:$('#trackingShipmentNo').value,carrier:$('#trackingCarrier').value,trackingNo:$('#trackingNo').value});$('#trackingDialog').close();await refresh();toast('运单号已保存')}catch(x){toast(x.message)}};
$('#chooseFileBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{const f=e.target.files?.[0];if(f)importWorkbook(f).catch(x=>toast(x.message))};const dz=$('#dropZone');dz.ondragover=e=>{e.preventDefault();dz.style.borderColor='#0071e3'};dz.ondragleave=()=>dz.style.borderColor='';dz.ondrop=e=>{e.preventDefault();dz.style.borderColor='';const f=e.dataTransfer.files?.[0];if(f)importWorkbook(f).catch(x=>toast(x.message))};$('#exportBtn').onclick=()=>exportWorkbook().catch(x=>toast(x.message));
refresh();
