/* WRITE V10 production runtime — V10.6.6 export delegation closure */
(function(g){'use strict';const VERSION='10.1.0';
function build(){const b=g.WRITE_V8_SOURCE_BRIDGE?.();if(!b?.orders)return null;const all=g.WRITE_V10_PRODUCTION.build(b.orders);const result={version:VERSION,...all,mode:'PRODUCTION',rolloutPercent:100};g.WRITE_V10_LAST=result;return result}
function removeLegacyDebugPanels(){for(const id of ['v85MultiDatasetPanel','v86BatchScorePanel','v87ClosurePanel','v88AutoExtractPanel','v9ProductionPanel','v8ShadowPanel','v8TrainingPanel','v8ZeroLossPanel'])document.getElementById(id)?.remove()}
function installUi(){removeLegacyDebugPanels();const p=document.querySelector('[data-view-panel="quality"]');if(!p||document.getElementById('v10QualityPanel'))return;const e=document.createElement('section');e.id='v10QualityPanel';e.className='panel wide v10-quality-panel';e.innerHTML='<div class="panel-head"><div><h2>V10 数据质量</h2><p>订单完整性、FACT统计和异常审核</p></div><span>PRODUCTION</span></div><div class="v8-audit-grid" id="v10Metrics"></div><div id="v10Gate"></div>';p.appendChild(e)}
function render(){installUi();const x=build();if(!x)return;const a=x.audit,host=document.getElementById('v10Metrics'),gate=document.getElementById('v10Gate');if(!host)return;host.innerHTML=[['有效包裹',a.parcelCount],['赠品专单排除',a.giftOnlyExcludedParcels],['精确去重',a.deduplicatedRecords],['冲突订单',a.conflictOrderIds.length],['FACT统计行',x.rows.length],['数据守恒',a.hardPass?'PASS':'FAIL']].map(([k,v])=>`<article><span>${k}</span><strong>${v}</strong></article>`).join('');gate.innerHTML=a.hardPass?'<div class="success-strip">✓ 导出为统一 XLSX：FACT 第一张 + 会计统计 + 学习溯源。</div>':'<div class="error-card" style="display:block">数据守恒失败，请人工复核。</div>'}
async function exportAll(){if(!g.WRITE_V10_EXPORT?.downloadProductionPackage)throw new Error('V10_EXPORT_RUNTIME_UNAVAILABLE');return await g.WRITE_V10_EXPORT.downloadProductionPackage()}
function installExportTakeover(){const ids=['exportButton','heroExportButton','topExportButton','quickExportButton'];document.addEventListener('click',e=>{const button=e.target?.closest?.('button');if(!button||!ids.includes(button.id))return;if(g.WRITE_V1064_EXPORT_AUTHORITY||g.WRITE_V1066_EXPORT_AUTHORITY)return;e.preventDefault();e.stopImmediatePropagation();const old=button.innerHTML;button.disabled=true;button.textContent='正在生成统一结算 Excel…';exportAll().then(r=>{const n=Number(r?.workbooks||0);button.textContent=n?`已下载 ${n} 个统一 XLSX`:'导出完成';setTimeout(()=>button.innerHTML=old,2600)}).catch(err=>{console.error(err);button.textContent=`导出失败：${err.message}`;setTimeout(()=>button.innerHTML=old,5000)}).finally(()=>button.disabled=false)},true)}
function start(){removeLegacyDebugPanels();installUi();installExportTakeover();setTimeout(render,1000);window.addEventListener('write-import-complete',()=>setTimeout(render,400))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();g.WRITE_V10_RUNTIME={VERSION,build,render,exportAll,mode:'PRODUCTION'};
})(window);