/* WRITE V10.2.7 — audited learned-price recovery */
(function(g){'use strict';
const VERSION='10.2.7';
const P={
'FRANCE|1':[0.85,5.06,5.91],'FRANCE|2':[1.7,8.07,9.77],'FRANCE|3':[2.55,11.01,13.56],'FRANCE|4':[3.4,13.93,17.33],'FRANCE|5':[4.25,17.78,22.03],'FRANCE|6':[5.1,20.92,26.02],'FRANCE|7':[5.95,24.05,30],'FRANCE|9':[7.65,30.32,37.97],'FRANCE|10':[8.5,33.46,41.96],'FRANCE|12':[11.3,34.48,45.78],'FRANCE|15':[12.75,40.07,52.82],'FRANCE|20':[17,49.39,66.39],'FRANCE|21':[17.85,46.2,64.05],'FRANCE|24':[20.4,56.84,77.24],'FRANCE|48':[40.8,77.2,118],
'BELGIUM|1':[0.85,4.64,5.49],'BELGIUM|2':[1.7,7.58,9.28],'BELGIUM|3':[2.55,10.52,13.07],'BELGIUM|4':[3.4,13.46,16.86],'BELGIUM|5':[4.25,16.41,20.66],'BELGIUM|6':[5.1,19.35,24.45],'BELGIUM|8':[6.8,25.23,32.03],'BELGIUM|9':[7.65,28.17,35.82],
'CANADA|1':[0.85,5.29,6.14],'CANADA|2':[1.7,8.37,10.07],'CANADA|3':[2.55,11.46,14.01],'CANADA|4':[3.4,18.06,21.46],'CANADA|5':[4.25,21.7,25.95],'CANADA|6':[5.1,25.34,30.44],
'SWITZERLAND|1':[0.85,5.49,6.34],'SWITZERLAND|2':[1.7,9.78,11.48],'SWITZERLAND|3':[2.55,14,16.55],'SWITZERLAND|4':[3.4,18.36,21.76],'SWITZERLAND|5':[4.25,22.66,26.91],'SWITZERLAND|6':[5.1,26.95,32.05],'SWITZERLAND|7':[5.95,31.24,37.19],'SWITZERLAND|8':[6.8,35.53,42.33],'SWITZERLAND|9':[7.65,39.82,47.47],'SWITZERLAND|12':[10.2,46.89,57.09],
'LUXEMBOURG|2':[1.7,10.69,12.39],'LUXEMBOURG|3':[2.55,14.79,17.34],'LUXEMBOURG|4':[3.4,18.88,22.28],
'GERMANY|1':[0.85,5.76,6.61],'GERMANY|2':[1.7,9.98,11.68],'GERMANY|3':[2.55,14.68,17.23]};
const U={FRANCE:{LOT4:.76,LOT6:1.49,COLOR:.25},BELGIUM:{LOT4:.76,LOT6:1.49,COLOR:.25},CANADA:{LOT4:.76,LOT6:1.49,COLOR:.25},SWITZERLAND:{LOT4:.76,LOT6:2.55,COLOR:.25},LUXEMBOURG:{LOT4:.79,LOT6:2.73,COLOR:.25},GERMANY:{LOT4:.76,LOT6:1.79,COLOR:.25}};
const clean=v=>String(v??'').replace(/\r/g,' ').replace(/\s+/g,' ').trim(),upper=v=>clean(v).toUpperCase(),round2=n=>Math.round((Number(n)+Number.EPSILON)*100)/100;
function pencilUnits(r={}){const e=Array.isArray(r.rawEvidence)?r.rawEvidence:[],t=e.filter(x=>String(x.family)==='PENCIL_MAIN').reduce((s,x)=>s+(Number(x.multiplicity)||0),0),q=Number(r.quantity)||1,p=t/q;return Number.isFinite(p)&&p>0&&Math.abs(p-Math.round(p))<1e-9?Math.round(p):0}
function kind(r={}){const t=clean(r.description).toLowerCase();if(/lot de 4|4 mines rechargeables/.test(t))return'LOT4';if(/lot de 6|6 mines color/.test(t))return'LOT6';if(/mines color/.test(t))return'COLOR';if(/coffret cadeau|gift box/.test(t))return'BOX';if(/gravure|engraving/.test(t))return'ENGRAVE';return''}
function verifiedPrice(r={}){const c=upper(r.country),cur=upper(r.currency||'EUR');if(cur!=='EUR')return null;if(r.role==='PACKAGE'){const n=pencilUnits(r),x=P[c+'|'+n];return x?{cogs:x[0],shipping:x[1],unitTotal:x[2],description:'Stylo eternelX'+n,source:'AUDITED_FACT_10063_COUNTRY_PENCIL_QTY',ruleId:'V1027-'+c+'-X'+n}:null}const k=kind(r);if(k==='BOX')return{cogs:null,shipping:1.25,unitTotal:1.25,source:'AUDITED_FACT_10063_GLOBAL_UPSELL',ruleId:'V1027-BOX'};if(k==='ENGRAVE')return{cogs:.6,shipping:null,unitTotal:.6,source:'AUDITED_FACT_10063_GLOBAL_SERVICE',ruleId:'V1027-ENGRAVE'};const v=U[c]?.[k];return Number.isFinite(Number(v))?{cogs:Number(v),shipping:null,unitTotal:Number(v),source:'AUDITED_FACT_10063_COUNTRY_UPSELL',ruleId:'V1027-'+c+'-'+k}:null}
function price(r){if(r.unitTotal!==null&&r.unitTotal!==undefined&&r.unitTotal!=='')return r;let p=null;try{const c=g.WRITE_KB?.calculateCost?.({sku:'CONFIG:'+String(r.configurationFingerprint||''),productName:r.description,country:r.country,currency:r.currency,quantity:1,orderAmount:0});if(c?.resolved)p={cogs:c.unitCost,shipping:0,unitTotal:c.unitCost,source:'CLOUD_CONFIG_COST_MODEL',ruleId:c.rule?.ruleId||''}}catch{}if(!p)p=verifiedPrice(r);if(!p)return r;if(p.description)r.description=p.description;r.cogs=p.cogs;r.shipping=p.shipping;r.unitTotal=Number(p.unitTotal);r.amount=round2(r.unitTotal*(Number(r.quantity)||0));r.priceBlank=false;r.needsReview=false;r.learnedFromReviewedWorkbook=true;r.priceSource=p.source;r.priceRuleId=p.ruleId;return r}
function merge(rows=[]){const m=new Map(),o=[];for(const r of rows){if(r.role==='PACKAGE'){const n=pencilUnits(r);if(n){const k=[r.invoiceEntity,r.origin,r.country,r.currency,r.taxRegime,'PACKAGE','PENCIL_X'+n].join('\u0001');let x=m.get(k);if(!x){x={...r,description:'Stylo eternelX'+n,configurationFingerprint:'PENCIL_X'+n,quantity:0,sourceOrderKeys:[],sourceItemKeys:[],trackingNumbers:[],rawEvidence:[],needsReview:false};m.set(k,x)}x.quantity+=Number(r.quantity)||0;x.sourceOrderKeys.push(...(r.sourceOrderKeys||[]));x.sourceItemKeys.push(...(r.sourceItemKeys||[]));x.trackingNumbers.push(...(r.trackingNumbers||[]));x.rawEvidence.push(...(r.rawEvidence||[]));continue}}o.push(r)}const a=[...m.values(),...o];a.forEach(price);a.sort((x,y)=>String(x.country).localeCompare(String(y.country))||String(x.role).localeCompare(String(y.role))||String(x.description).localeCompare(String(y.description),'fr',{numeric:true}));a.forEach((r,i)=>r.no=i+1);a.parcelCount=rows.parcelCount;a.parcelNeedsReview=rows.parcelNeedsReview;return a}
function patchAtoms(){const A=g.WRITE_V10_ATOMS;if(!A?.parseSourceItem||A.__v1027)return;const f=A.parseSourceItem.bind(A);A.parseSourceItem=(i,c)=>{const a=f(i,c)||[];for(const x of a)if(x.role!=='FREE_GIFT'&&(x.family==='PAID_GIFT_BOX'||x.family==='PENCIL_REFILL'))x.role='UPSELL';return a};A.__v1027=true}
function patchProd(){const X=g.WRITE_V10_PRODUCTION;if(!X?.build||X.__v1027)return;const f=X.build.bind(X);X.build=i=>{const r=f(i);r.rows=merge(r.rows||[]);r.version=VERSION;return r};X.__v1027=true}
function fixNav(){if(typeof document==='undefined')return;const n=document.querySelector('.nav-item[data-view="learning"]');if(!n)return;const b=n.querySelector('b')?.outerHTML||'';n.innerHTML='<span class="v1027-nav-icon">⌘</span><span class="v1027-nav-label">数据管理</span>'+b;n.title='数据管理';if(!document.getElementById('v1027NavStyle')){const s=document.createElement('style');s.id='v1027NavStyle';s.textContent='.nav-item[data-view="learning"]{display:flex!important;align-items:center!important;gap:10px!important}.v1027-nav-icon{font-size:13px!important;line-height:1!important;flex:0 0 16px;text-align:center}.v1027-nav-label{font-size:12px!important;line-height:1.2!important;font-weight:inherit!important;white-space:nowrap}';document.head.appendChild(s)}}
function hist(){if(typeof document!=='undefined'){document.body.dataset.release=VERSION;document.querySelectorAll('.brand-copy small').forEach(x=>x.textContent='v'+VERSION+' Production')}const M=g.WRITE_RELEASE_META;if(M){const e={version:VERSION,time:'2026-08-13 11:10',title:'Learned Price Recovery + Data Management UI Fix',items:['修复已学习订单仍全红且成本为空。','PACKAGE 恢复国家 + 铅笔件数 Xn 聚合。','Coffret Cadeau/笔芯独立 UPSELL；Gravure 独立 SERVICE。','修复数据管理菜单图标与字号。','无可信价格继续标红，不猜价。']};M.current={version:VERSION,time:e.time,title:e.title,sections:[{label:'V10.2.7',items:e.items}]};M.history=[e,...(M.history||[]).filter(x=>String(x.version)!==VERSION)];g.WRITE_CLOUD_RULE_LIBRARY?.repairHistory?.()}}
function start(){patchAtoms();patchProd();fixNav();hist();setTimeout(()=>{patchAtoms();patchProd();fixNav();hist()},300)}
if(typeof document!=='undefined'){document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start):start()}else{patchAtoms();patchProd()}
g.WRITE_V1027_HOTFIX={VERSION,_test:{verifiedPrice,pencilUnits,merge}};
})(typeof window!=='undefined'?window:globalThis);
