/* WRITE V10.2.9 FINAL */
(function(g){'use strict';
const VERSION='10.2.9';
const SHIPPING={FRANCE:{1:5.06,2:8.07,3:11.01,4:13.93,5:17.78,6:20.92,7:24.05,9:30.32,10:33.46,12:34.48,15:40.07,20:49.39,21:46.2,24:56.84,48:77.2},BELGIUM:{1:4.64,2:7.58,3:10.52,4:13.46,5:16.41,6:19.35,8:25.23,9:28.17},CANADA:{1:5.29,2:8.37,3:11.46,4:18.06,5:21.7,6:25.34},SWITZERLAND:{1:5.49,2:9.78,3:14,4:18.36,5:22.66,6:26.95,7:31.24,8:35.53,9:39.82,12:46.89},LUXEMBOURG:{1:5.49,2:10.69,3:14.79,4:18.88},GERMANY:{1:5.76,2:9.98,3:14.68}};
const FALLBACK={PENCIL_MAIN:.85,PAID_GIFT_BOX:1.25,REFILL_LOT4:.76,REFILL_LOT6:1.49,REFILL_COLOR:.25};
const clean=v=>String(v??'').replace(/\r/g,' ').replace(/\s+/g,' ').trim(),upper=v=>clean(v).toUpperCase(),round2=n=>Math.round((Number(n)+Number.EPSILON)*100)/100;
const baseSku=v=>clean(v).replace(/\s*(?:\*|x|×)\s*\d+(?:[.,]\d+)?\s*$/i,'').trim();
function refillKind(e={}){const t=clean(e.shortDescription||e.rawProductName).toLowerCase();if(/lot de 4|4 mines rechargeables/.test(t))return'REFILL_LOT4';if(/lot de 6|pack de 6|6 mines color/.test(t))return'REFILL_LOT6';if(/mines color/.test(t))return'REFILL_COLOR';return''}
function displayName(e={}){if(e.family==='PENCIL_MAIN')return'Stylo eternel';if(e.family==='PAID_GIFT_BOX')return'Coffret Cadeau';const k=refillKind(e);if(k==='REFILL_LOT4')return'Lot de 4 mines rechargeables';if(k==='REFILL_LOT6')return'Lot de 6 Mines colorées';if(k==='REFILL_COLOR')return'Mines colorées';return clean(e.shortDescription||e.rawProductName||e.sku||'Article')}
function componentCost(e,row){const sku=baseSku(e.sku),name=clean(e.shortDescription||e.rawProductName);for(const p of[{sku,productName:name,country:row.country,currency:row.currency,quantity:1,orderAmount:0},{sku,productName:name,country:'',currency:row.currency,quantity:1,orderAmount:0}])try{const c=g.WRITE_KB?.calculateCost?.(p);if(c?.resolved&&Number.isFinite(Number(c.unitCost)))return Number(c.unitCost)}catch{}const k=refillKind(e);if(e.family==='PENCIL_MAIN')return FALLBACK.PENCIL_MAIN;if(e.family==='PAID_GIFT_BOX')return FALLBACK.PAID_GIFT_BOX;if(k&&Number.isFinite(Number(FALLBACK[k])))return Number(FALLBACK[k]);return null}
function shippingFor(country,pencils){const m=SHIPPING[upper(country)]||{},n=pencils||1;return Number.isFinite(Number(m[n]))?Number(m[n]):null}
function evidence(res){const seen=new Set(),out=[];for(const row of(res.rows||[])){if(!['PACKAGE','UPSELL','FREE_GIFT'].includes(String(row.role)))continue;for(const z of(row.rawEvidence||[])){const e={...z,_role:String(row.role),_country:row.country,_currency:row.currency,_origin:row.origin,_entity:row.invoiceEntity,_tax:row.taxRegime};const k=clean(e.sourceItemKey)||[e.orderId,baseSku(e.sku),displayName(e),e.multiplicity,e._role].join('|');if(seen.has(k))continue;seen.add(k);out.push(e)}}return out}
function salesSummary(res){const ev=evidence(res),orders=new Map();for(const e of ev){const id=clean(e.orderId)||'UNKNOWN';if(!orders.has(id))orders.set(id,[]);orders.get(id).push(e)}const multi=new Set();for(const[id,list]of orders){const units=list.filter(e=>e._role!=='FREE_GIFT').reduce((s,e)=>s+(Number(e.multiplicity)||1),0),types=new Set(list.filter(e=>e._role!=='FREE_GIFT').map(displayName));if(units>1||types.size>1)multi.add(id)}const map=new Map();for(const e of ev){const name=displayName(e),sku=baseSku(e.sku),k=name+'|'+sku;let x=map.get(k);if(!x)x={product:name,sku,paidQty:0,giftQty:0,totalQty:0,multiItemQty:0,orders:new Set()};const q=Number(e.multiplicity)||1,id=clean(e.orderId)||'UNKNOWN';if(e._role==='FREE_GIFT')x.giftQty+=q;else{x.paidQty+=q;if(multi.has(id))x.multiItemQty+=q}x.totalQty+=q;x.orders.add(id);map.set(k,x)}return[...map.values()].map(x=>({...x,involvedOrders:x.orders.size,orders:undefined})).sort((a,b)=>b.totalQty-a.totalQty||a.product.localeCompare(b.product,'fr'))}
function packageRows(res){const paid=evidence(res).filter(e=>e._role!=='FREE_GIFT'),orders=new Map();for(const e of paid){const id=clean(e.orderId)||'UNKNOWN';if(!orders.has(id))orders.set(id,[]);orders.get(id).push(e)}const groups=new Map();for(const[id,list]of orders){if(!list.length)continue;const f=list[0],counts=new Map(),raw=[];let cogs=0,pencils=0,unknown=false;for(const e of list){const q=Number(e.multiplicity)||1,n=displayName(e);counts.set(n,(counts.get(n)||0)+q);raw.push(e);if(e.family==='PENCIL_MAIN')pencils+=q;const u=componentCost(e,{country:f._country,currency:f._currency});if(u===null)unknown=true;else cogs+=u*q}const ship=shippingFor(f._country,pencils);if(ship===null)unknown=true;const arr=[...counts.entries()].sort((a,b)=>{const r=n=>n==='Stylo eternel'?0:n==='Coffret Cadeau'?1:/Lot de 4/.test(n)?2:/Lot de 6/.test(n)?3:4;return r(a[0])-r(b[0])||a[0].localeCompare(b[0],'fr')});const desc=arr.map(([n,q])=>`${n} *${q}`).join(' + '),fp=arr.map(([n,q])=>`${n}\u0002${q}`).join('\u0003'),k=[f._entity,f._origin,f._country,f._currency,f._tax,fp].join('\u0001');let x=groups.get(k);if(!x)x={invoiceEntity:f._entity,origin:f._origin,country:f._country,currency:f._currency,taxRegime:f._tax,role:'PACKAGE',description:desc,configurationFingerprint:fp,quantity:0,cogs:unknown?null:round2(cogs),shipping:unknown?null:round2(ship),unitTotal:unknown?null:round2(cogs+ship),amount:unknown?null:0,needsReview:unknown,priceBlank:unknown,sourceOrderKeys:[],rawEvidence:[]};x.quantity++;x.sourceOrderKeys.push(id);x.rawEvidence.push(...raw);if(x.unitTotal!==null)x.amount=round2(x.unitTotal*x.quantity);groups.set(k,x)}return[...groups.values()]}
function rebuild(res){const old=res.rows||[],rows=[...packageRows(res),...old.filter(r=>['SERVICE','FEE'].includes(String(r.role)))];rows.sort((a,b)=>String(a.country).localeCompare(String(b.country))||String(a.role).localeCompare(String(b.role))||String(a.description).localeCompare(String(b.description),'fr',{numeric:true}));rows.forEach((r,i)=>r.no=i+1);rows.parcelCount=old.parcelCount;rows.parcelNeedsReview=rows.some(r=>r.needsReview);res.rows=rows;res.productSalesSummary=salesSummary({rows:old});res.version=VERSION;return res}
function patchProduction(){const X=g.WRITE_V10_PRODUCTION;if(!X?.build||X.__v1029)return;const b=X.build.bind(X);X.build=i=>rebuild(b(i));X.__v1029=true}
const enc=new TextEncoder(),dec=new TextDecoder(),esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function maxRow(x){return Math.max(0,...[...x.matchAll(/<row\b[^>]*\br="(\d+)"/g)].map(m=>+m[1]))}function styleOf(x,r){return /\bs="(\d+)"/.exec((new RegExp(`<c\\b[^>]*\\br="${r}"[^>]*>`)).exec(x)?.[0]||'')?.[1]||''}function col(n){let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)}return s}function c(ref,v,s=''){const st=s?` s="${s}"`:'';if(v==null||v==='')return`<c r="${ref}"${st}/>`;if(typeof v==='number')return`<c r="${ref}"${st}><v>${v}</v></c>`;return`<c r="${ref}"${st} t="inlineStr"><is><t xml:space="preserve">${esc(v)}</t></is></c>`}
function appendSummaryXml(x,sum){if(!sum?.length)return x;const mr=maxRow(x),start=mr+2,hs=[2,3,4,5,6,7,8].map(n=>styleOf(x,col(n)+'10')),ds=[2,3,4,5,6,7,8].map(n=>styleOf(x,col(n)+'12'));let rows=`<row r="${start}">${c('B'+start,'PRODUCT SALES SUMMARY / 商品销售统计',styleOf(x,'B8')||hs[0])}</row>`;const h=['产品','SKU','销售数量','赠品数量','总件数','其中多商品订单','涉及订单'];rows+=`<row r="${start+1}">${h.map((v,i)=>c(col(i+2)+(start+1),v,hs[i])).join('')}</row>`;sum.forEach((v,j)=>{const r=start+2+j,a=[v.product,v.sku,v.paidQty,v.giftQty,v.totalQty,v.multiItemQty,v.involvedOrders];rows+=`<row r="${r}">${a.map((q,i)=>c(col(i+2)+r,q,ds[i])).join('')}</row>`});return x.replace('</sheetData>',rows+'</sheetData>')}
function patchWorkbook(){const W=g.WRITE_V101_WORKBOOK;if(!W?.mergeFactAndAccounting||W.__v1029)return;const b=W.mergeFactAndAccounting.bind(W);W.mergeFactAndAccounting=async function(f,a,res,n){const blob=await b(f,a,res,n),sum=res?.productSalesSummary||[];if(!sum.length)return blob;const m=await W.readZip(blob),w=dec.decode(m.get('xl/workbook.xml')),rs=W.rels(dec.decode(m.get('xl/_rels/workbook.xml.rels'))),sh=W.sheets(w).find(x=>String(x.name).toUpperCase()==='FACT')||W.sheets(w)[0];if(!sh)return blob;let t=rs.get(sh.rid);if(!t)return blob;t=t.startsWith('/xl/')?t.slice(1):(t.startsWith('xl/')?t:'xl/'+t.replace(/^\//,''));if(!m.has(t))return blob;m.set(t,enc.encode(appendSummaryXml(dec.decode(m.get(t)),sum)));return W.writeZip(m)};W.__v1029=true}
let repairing=false;function fixNav(){if(typeof document==='undefined'||repairing)return;const n=document.querySelector('.nav-item[data-view="learning"]');if(!n)return;const good=n.querySelectorAll(':scope>.v1029-nav-icon').length===1&&n.querySelectorAll(':scope>.v1029-nav-label').length===1&&clean(n.textContent)==='⌘数据管理';if(good)return;repairing=true;n.replaceChildren();const i=document.createElement('span'),l=document.createElement('span');i.className='v1029-nav-icon';i.textContent='⌘';l.className='v1029-nav-label';l.textContent='数据管理';n.append(i,l);repairing=false}
function lockNav(){if(typeof document==='undefined')return;let s=document.getElementById('v1029NavStyle');if(!s){s=document.createElement('style');s.id='v1029NavStyle';document.head.appendChild(s)}s.textContent='.nav-item[data-view="learning"]{font-size:0!important;display:grid!important;grid-template-columns:18px 1fr!important;align-items:center!important;gap:10px!important}.nav-item[data-view="learning"]>*:not(.v1029-nav-icon):not(.v1029-nav-label){display:none!important}.v1029-nav-icon{font-size:13px!important;line-height:1!important;text-align:center!important}.v1029-nav-label{font-size:12px!important;line-height:1.2!important;font-weight:600!important;white-space:nowrap!important}';fixNav();const r=document.getElementById('sideNav');if(r&&!r.__v1029){const o=new MutationObserver(fixNav);o.observe(r,{childList:true,subtree:true,characterData:true,attributes:true});r.__v1029=o}}
function start(){patchProduction();patchWorkbook();lockNav();setTimeout(()=>{patchProduction();patchWorkbook();lockNav()},400)}if(typeof document!=='undefined'){document.readyState==='loading'?document.addEventListener('DOMContentLoaded',start):start()}else{patchProduction();patchWorkbook()}g.WRITE_V1029_HOTFIX={VERSION,_test:{displayName,shippingFor,salesSummary,packageRows,rebuild,appendSummaryXml}};
})(typeof window!=='undefined'?window:globalThis);
