/* WRITE V10 local XLS (BIFF8/OLE2) reader — no network dependency. */
(function(g){'use strict';const VERSION='10.0.0-rc1';
const FREE=0xffffffff,END=0xfffffffe,FATSECT=0xfffffffd,DIFSECT=0xfffffffc;
function u16(b,o){return b[o]|(b[o+1]<<8)}function u32(b,o){return (b[o]|(b[o+1]<<8)|(b[o+2]<<16)|(b[o+3]<<24))>>>0}
function i32(b,o){return (u32(b,o)|0)}function f64(b,o){return new DataView(b.buffer,b.byteOffset+o,8).getFloat64(0,true)}
function utf16(b,o,n){let s='';for(let i=0;i<n;i++)s+=String.fromCharCode(u16(b,o+i*2));return s.replace(/\0+$/,'')}
function ascii(b,o,n){return new TextDecoder('windows-1252',{fatal:false}).decode(b.slice(o,o+n)).replace(/\0+$/,'')}
function cfb(bytes){const b=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes);if(u32(b,0)!==0xe011cfd0||u32(b,4)!==0xe11ab1a1)throw new Error('XLS_OLE_SIGNATURE_INVALID');
 const sectorSize=1<<u16(b,30),miniSize=1<<u16(b,32),fatCount=u32(b,44),dirStart=u32(b,48),miniCut=u32(b,56),miniFatStart=u32(b,60),miniFatCount=u32(b,64),difStart=u32(b,68),difCount=u32(b,72);const sector=id=>b.slice(512+id*sectorSize,512+(id+1)*sectorSize);
 let fatSectors=[];for(let i=0;i<109;i++){const id=u32(b,76+i*4);if(id!==FREE)fatSectors.push(id)}let next=difStart;for(let d=0;d<difCount&&next!==END&&next!==FREE;d++){const s=sector(next),n=sectorSize/4-1;for(let i=0;i<n;i++){const id=u32(s,i*4);if(id!==FREE)fatSectors.push(id)}next=u32(s,n*4)}fatSectors=fatSectors.slice(0,fatCount);
 const FAT=[];for(const id of fatSectors){const s=sector(id);for(let i=0;i<sectorSize;i+=4)FAT.push(u32(s,i))}
 function chain(start,table=FAT,limit=100000){const ids=[],seen=new Set();let x=start;while(x!==END&&x!==FREE&&x<table.length&&!seen.has(x)&&ids.length<limit){seen.add(x);ids.push(x);x=table[x]>>>0}return ids}
 function readRegular(start,size=Infinity){const ids=chain(start),parts=ids.map(sector),out=new Uint8Array(parts.length*sectorSize);parts.forEach((p,i)=>out.set(p,i*sectorSize));return out.slice(0,Math.min(size,out.length))}
 const dir=readRegular(dirStart),entries=[];for(let o=0;o+128<=dir.length;o+=128){const nameLen=u16(dir,o+64),name=nameLen>=2?utf16(dir,o,(nameLen/2)-1):'',type=dir[o+66],start=u32(dir,o+116),sizeLo=u32(dir,o+120),sizeHi=u32(dir,o+124),size=Number(BigInt(sizeHi)*4294967296n+BigInt(sizeLo));if(name)entries.push({name,type,start,size})}
 const root=entries.find(e=>e.type===5),work=entries.find(e=>e.type===2&&/^(Workbook|Book)$/i.test(e.name));if(!work)throw new Error('XLS_WORKBOOK_STREAM_MISSING');let miniFAT=[],miniStream=null;if(miniFatCount&&miniFatStart!==END&&root){const mf=readRegular(miniFatStart,miniFatCount*sectorSize);for(let i=0;i+4<=mf.length;i+=4)miniFAT.push(u32(mf,i));miniStream=readRegular(root.start,root.size)}
 function readStream(e){if(e.size<miniCut&&miniStream&&miniFAT.length){const ids=chain(e.start,miniFAT),out=new Uint8Array(ids.length*miniSize);ids.forEach((id,i)=>out.set(miniStream.slice(id*miniSize,id*miniSize+miniSize),i*miniSize));return out.slice(0,e.size)}return readRegular(e.start,e.size)}
 return readStream(work)}
function readXLUnicode(buf,pos){if(pos+3>buf.length)return{value:'',next:buf.length};const cch=u16(buf,pos);pos+=2;const flags=buf[pos++],high=!!(flags&1),rich=!!(flags&8),ext=!!(flags&4);let runs=0,extLen=0;if(rich){runs=u16(buf,pos);pos+=2}if(ext){extLen=u32(buf,pos);pos+=4}const need=cch*(high?2:1);if(pos+need>buf.length)return{value:'',next:buf.length};const value=high?utf16(buf,pos,cch):ascii(buf,pos,cch);pos+=need+(runs*4)+extLen;return{value,next:pos}}
function parseSST(payload){if(payload.length<8)return[];const unique=u32(payload,4),out=[];let p=8;for(let i=0;i<unique&&p<payload.length;i++){const x=readXLUnicode(payload,p);out.push(x.value);if(x.next<=p)break;p=x.next}return out}
function decodeRK(v){const mult100=v&1,isInt=v&2;let n;if(isInt)n=(v>>2);else{const buf=new ArrayBuffer(8),dv=new DataView(buf);dv.setUint32(4,v&0xfffffffc,true);n=dv.getFloat64(0,true)}return mult100?n/100:n}
function workbook(bytes){const b=cfb(bytes),bounds=[],sstParts=[];let p=0;while(p+4<=b.length){const id=u16(b,p),len=u16(b,p+2),d=b.slice(p+4,p+4+len);if(id===0x0085&&len>=8){const off=u32(d,0),cch=d[6],flags=d[7],name=(flags&1)?utf16(d,8,cch):ascii(d,8,cch);bounds.push({offset:off,name})}if(id===0x00fc||((id===0x003c)&&sstParts.length))sstParts.push(d);p+=4+len;if(id===0x000a&&bounds.length){} }
 const sst=sstParts.length?parseSST((()=>{const n=sstParts.reduce((s,x)=>s+x.length,0),o=new Uint8Array(n);let q=0;for(const x of sstParts){o.set(x,q);q+=x.length}return o})()):[];const sheets=[];
 for(const bs of bounds){const cells=new Map();let maxR=0,maxC=0,q=bs.offset;while(q+4<=b.length){const id=u16(b,q),len=u16(b,q+2),d=b.slice(q+4,q+4+len);if(id===0x000a)break;if(len>=6){const r=u16(d,0),c=u16(d,2);let val=null;if(id===0x00fd&&len>=10)val=sst[u32(d,6)]??'';else if(id===0x0203&&len>=14)val=f64(d,6);else if(id===0x027e&&len>=10)val=decodeRK(i32(d,6));else if(id===0x0204&&len>=8){const n=u16(d,6);val=ascii(d,8,Math.min(n,len-8))}if(val!==null){cells.set(`${r}:${c}`,val);if(r>maxR)maxR=r;if(c>maxC)maxC=c}}q+=4+len}
  const rows=[];for(let r=0;r<=maxR;r++){const row=[];for(let c=0;c<=maxC;c++)row.push(cells.get(`${r}:${c}`)??'');rows.push(row)}sheets.push({name:bs.name,rows})}
 return{version:VERSION,sheets}}
function records(bytes){const wb=workbook(bytes),all=[];for(const sh of wb.sheets){if(!sh.rows.length)continue;let h=0,best=-1;for(let r=0;r<Math.min(10,sh.rows.length);r++){const score=sh.rows[r].filter(x=>String(x).trim()).length;if(score>best){best=score;h=r}}const heads=sh.rows[h].map((x,i)=>String(x||`COL_${i+1}`).trim());for(let r=h+1;r<sh.rows.length;r++){if(!sh.rows[r].some(x=>String(x).trim()))continue;const o=Object.fromEntries(heads.map((k,i)=>[k,sh.rows[r][i]??'']));o.__sheet=sh.name;all.push(o)}}return all}
g.WRITE_V10_XLS={VERSION,cfb,workbook,records};if(g.WRITE_V10_INGESTION?.registerLocalXlsAdapter)g.WRITE_V10_INGESTION.registerLocalXlsAdapter(async b=>records(b));
})(typeof window!=='undefined'?window:globalThis);
