/* WRITE V9.0 Red Review — changes auto-learn, no extra learning prompt */
(function(g){'use strict';let current=[];const saved=new Map(),html=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'),attr=v=>html(v).replace(/"/g,'&quot;');
function panel(){let e=document.getElementById('v9ReviewPanel');if(e)return e;const p=document.querySelector('[data-view-panel="review"] .panel')||document.querySelector('[data-view-panel="dashboard"] .dashboard-grid');if(!p)return null;e=document.createElement('section');e.id='v9ReviewPanel';e.className='panel wide v9-review-panel';e.innerHTML='<div class="panel-head"><div><h2>V9 红字审核</h2><p>红字=低置信度；正式FACT不写“待确认”文字。</p></div><span id="v9ReviewStatus">0 条</span></div><div id="v9ReviewRows"></div>';p.appendChild(e);return e}
function collect(){const b=g.WRITE_V8_SOURCE_BRIDGE?.(),out=[];for(const w of b?.sourceWorkbooks||[]){const x=g.WRITE_V9_FACT_ENGINE?.buildWorkbookRows?.(w.name);for(const row of x?.rows||[])if(row.needsReview)for(const it of row.reviewItems||[])out.push({...it,country:row.country,origin:row.origin,configuration:row.description,workbookName:w.name})}const seen=new Set();return out.filter(x=>!seen.has(x.sourceItemKey)&&(seen.add(x.sourceItemKey),true))}
function syncLegacyCount(count){const nav=document.getElementById('navReviewCount'),quick=document.getElementById('quickReviewCount'),metric=document.getElementById('metricReview'),empty=document.getElementById('emptyReview');for(const e of [nav,quick,metric])if(e)e.textContent=String(count);if(nav)nav.hidden=count===0;if(empty)empty.hidden=count!==0}
function render(){panel();current=collect();syncLegacyCount(current.length);const host=document.getElementById('v9ReviewRows'),status=document.getElementById('v9ReviewStatus');if(!host||!status)return;status.textContent=`${current.length} 条`;if(!current.length){host.innerHTML='<div class="success-strip">✓ 当前没有红字审核项。</div>';return}host.innerHTML=`<div class="v9-review-list">${current.map((x,i)=>`<article class="v9-review-item"><div><b>${html(x.productName||x.sku||'Article')}</b><small>${html(x.country||'GLOBAL')} · ${html(x.sku||'无SKU')} · QTY ${html(x.quantity)}</small></div><input data-v9-desc="${i}" value="${attr(x.description)}"/><button data-v9-confirm="${i}">确认</button></article>`).join('')}</div>`;const save=async(i,val)=>{const x=current[i];if(!x)return;const description=val?.trim()||x.description,key=`${x.sourceItemKey}\u0001${description}`;if(saved.has(key))return;saved.set(key,true);try{await g.WRITE_V9_LEARNING.confirmCorrection({...x,description});render()}catch(e){saved.delete(key);throw e}};host.querySelectorAll('[data-v9-desc]').forEach(x=>x.addEventListener('change',e=>save(Number(e.target.dataset.v9Desc),e.target.value)));host.querySelectorAll('[data-v9-confirm]').forEach(x=>x.addEventListener('click',e=>{const i=Number(e.currentTarget.dataset.v9Confirm),inp=host.querySelector(`[data-v9-desc="${i}"]`);save(i,inp?.value)}))}
async function start(){await g.WRITE_V9_LEARNING?.init?.().catch(()=>{});panel();render();window.addEventListener('write-import-complete',()=>setTimeout(render,350))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();g.WRITE_V9_REVIEW={VERSION:'9.0.0',collect,render};
})(window);
